services:
  - type: web
    name: proyecticos-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: proyecticos-db
          property: connectionString

  - type: web
    name: proyecticos-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars: []

databases:
  - name: proyecticos-db
    databaseName: proyecticos
    user: proyecticos 